[package]
name = "diffusion-slice-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
# Raw data manipulations
bytemuck = { version = "1.16", features = ["derive"] }
clap = { version = "4.5.8", features = ["derive"] }
# Logging client
env_logger = "0.11"
# Fast math types
glam = { version = "0.32", features = ["bytemuck"] }
# Image encoders/decoders 
image = "0.25"
# Logging API
log = "0.4"
# Math types of trk-io
nalgebra = { version = "0.33", features = ["bytemuck"] }
ndarray = "0.16"
nifti = { version = "0.17", features = ["ndarray_volumes", "nalgebra_affine"] }
# Async runtime
pollster = "0.4"
trk-io = { version = "0.31", features = ["nifti_images"] }
# GPU API
wgpu = "29"
